site_name: Cognitive Storage and Computer Architecture Lab Doc
theme:
  name: material

nav:
  - 实验室介绍: docs/index.md
  - 新手村: docs/index.md
      - 服务器使用: docs/index.md
      - Docker使用: docs/index.md

